#! /usr/bin/python

import struct,sys
import pickle

args = sys.argv

def printhelp():
    print "print this help"

def mainstub():
    if len(args)<4:
        printhelp()
        return
    mode = args[1]
    filename = args[2]
    outfilename = args[3]
    contents=[]
    if "unpack" in mode:
        newcontents = pickle.load(open(filename,"r"))
        writeFile(outfilename,newcontents)#TODO remove output filename hardcoding
    elif "pack" in mode:
        val = getFileContents(filename)
        for v in val:
            newval = struct.pack("i",ord(v))
            contents.append(newval)
        pickle.dump(contents,open(outfilename,"w"))
    

def writeFile(filename,content):
    mybytes=[]
    for v in content:
        newbyte = struct.unpack("i",v)
        mybytes.append(newbyte[0])
    out_file = open(filename,"wb")
    out_file.write(bytearray(mybytes))
    out_file.close()

def getFileContents(filename):
    in_file = open(filename, "rb") # opening for [r]eading as [b]inary
    data = in_file.read() # if you only wanted to read 512 bytes, do .read(512)
    in_file.close()
    return data

mainstub()
